version: '3.1'

services:

  db:
    image: mysql
    container_name: agro_manager_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agromanager
      MYSQL_PASSWORD: root
    networks:
      - agromanager
    ports:
      - 3306:3306

  api:
    image: api
    container_name: agro_manager_api
    env_file:
      - .env
    restart: unless-stopped
    working_dir: /var/www/api
    volumes:
      - ./:/var/www/api
    depends_on: 
      - db
    # command: sh -c "npx prisma migrate dev && npx prisma db seed"
    networks:
      - agromanager
    ports:
      - 3000:3000

networks:
  agromanager:
    driver: bridge