version: '3.1'

services:

  db:
    image: mysql
    container_name: agro_manager_db
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306

  api:
    image: api
    container_name: agro_manager_api
    restart: unless-stopped
    working_dir: /var/www/api
    volumes:
      - ./:/var/www/api
    depends_on: 
      - db
    networks:
      - agromanager
    ports:
      - 3000:3000

networks:
  agromanager:
    driver: bridge